### ISSUE TITLE
Chocolatey upgrading? Emule forums announcement?

### ISSUE THREAD

**Issue by timofonic** [kurniliya/amule-for-windows#1]
Hello.

What about submitting an announcement in the eMule forums and other places? A Windows port could attract both users and developers, as the official client suffered "forkitis" and "abandonwaritis". 
Despite of that, it's an active network that needs a flux in form of new client. Has the changes been submitted in the main github repository? Why aren't you part of the Team and this is an official release? ;)

What about upgrading the Chocolatey packages?

https://chocolatey.org/packages/amule

Not sure where to reply, so I did it in the [amule forums](http://forum.amule.org/index.php?topic=21513.msg110053#msg110053) too. Sorry for the spam.

Kind regards.

**Comment by kurniliya** [comment]
Hi. Thanks for your enthusiasm.

This is a binary distribution. I compiled the binaries off *the very same* source code one can find in the [aMule repo](https://github.com/amule-project/amule/releases). There is [HowTo compile with Visual Studio](http://wiki.amule.org/wiki/HowTo_compile_with_Visual_Studio) instruction at aMule wiki. The instruction and Visual Studio projects are not exactly perfect, but are enough if you know what you're doing.

Here is a quote from the [aMule website](http://www.amule.org/) stating current position on the binary distributions:

> We offer no official binaries, (maybe except for Windows and MacOS, that's yet to be decided), so please bug your distro's maintainers to update their packages, or you can browse the list of [user-supplied packages](http://forum.amule.org/index.php?topic=21390.0).

As you have already discovered, I made the notification in relevant section of aMule forum. That actually *is* an official way of doing this kind of thing.

I'm not sure *e*Mule forums would be an appropriate place for any kind of *a*Mule notifications. And speaking of Chocolatey, I guess it's up to the package maintainer to update it. Though, I'm not at all familiar with Chocolatey community rules and customs.

Please, feel free to follow up shall you have any more questions or suggestions.
